steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-2025-1/joseph-672023095:v.1.0.release",
        "-f",
        "DockerFile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-2025-1/joseph-672023095:v.1.0.release",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "joseph-672023095"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/sat-kapita-selekta-b/ks-2025-1/joseph-672023095:v.1.0.release"
      - "--region"
      - "asia-southeast2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
